### ISSUE TITLE
It seems assemblyscript not support ``.

### ISSUE THREAD

**Issue by hsxyl** [vgrichina/web4#3]
```
export function web4_get(request: Web4Request): Web4Response {

    logging.log(`${storage.getString(WEB4_STATIC_URL_KEY)!}${request.path}`)
    let ipfs_path = storage.getString(WEB4_STATIC_URL_KEY) + request.path

    logging.log("ipfs path:" + ipfs_path)
    return bodyUrl(ipfs_path);
}
```

Then when we view `web4_get`: 
```
View call: web4bio.testnet.web4_get({"request": {"path": "/"}})
Log [web4bio.testnet]: ${storage.getString(WEB4_STATIC_URL_KEY)!}${request.path}
Log [web4bio.testnet]: ipfs path:https://bafybeihrni33utr5zv6tpsz6srapkadcji7xwcup6364gj3b4b6ow7esh4.ipfs.infura-ipfs.io/
```

**Comment by MaxGraey** [comment]
I'm not sure which AS version uses in NEAR now. But it looks like it has outdated loader:
https://github.com/near/near-sdk-as/blob/master/sdk/package.json#L27

However AS support template literals since [0.18.17](https://github.com/AssemblyScript/assemblyscript/releases/tag/v0.18.17)

**Comment by hsxyl** [comment]
> I'm not sure which AS version uses in NEAR now. But it looks like it has outdated loader: https://github.com/near/near-sdk-as/blob/master/sdk/package.json#L27
> 
> However AS support template literals since [0.18.17](https://github.com/AssemblyScript/assemblyscript/releases/tag/v0.18.17)

Oh, I see!
